//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolMSDataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;

    public partial class SchoolMSEntities : DbContext
    {
        public SchoolMSEntities()
            : base("name=SchoolMSEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
            this.Configuration.ProxyCreationEnabled = false;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<Class> Classes { get; set; }
        public virtual DbSet<ClassSubject> ClassSubjects { get; set; }
        public virtual DbSet<SchoolAcademic> SchoolAcademics { get; set; }
        public virtual DbSet<SchoolMaster> SchoolMasters { get; set; }
        public virtual DbSet<ClassSubject> ClassSubjects { get; set; }
        public virtual DbSet<SchoolClass> SchoolClasses { get; set; }
        public virtual DbSet<SchoolSubject> SchoolSubjects { get; set; }
        public virtual DbSet<Subject_Category> Subject_Category { get; set; }
        public virtual DbSet<SubjectsMaster> SubjectsMasters { get; set; }
        public virtual DbSet<Caste> Castes { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Disability> Disabilities { get; set; }
        public virtual DbSet<State> States { get; set; }
        public virtual DbSet<Student_Class_Details> Student_Class_Details { get; set; }
        public virtual DbSet<Student_communcation_Address> Student_communcation_Address { get; set; }
        public virtual DbSet<Student_Parent_Details> Student_Parent_Details { get; set; }
        public virtual DbSet<Student_Personal_Details> Student_Personal_Details { get; set; }
        public virtual DbSet<Religion> Religions { get; set; }
        public virtual DbSet<Nationality> Nationalities { get; set; }

        public virtual ObjectResult<GetClassSubject_Result> GetClassSubject(Nullable<int> classID, Nullable<int> schoolId)
        {
            var classIDParameter = classID.HasValue ?
                new ObjectParameter("classID", classID) :
                new ObjectParameter("classID", typeof(int));

            var schoolIdParameter = schoolId.HasValue ?
                new ObjectParameter("schoolId", schoolId) :
                new ObjectParameter("schoolId", typeof(int));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetClassSubject_Result>("GetClassSubject", classIDParameter, schoolIdParameter);
        }
    }
}
