//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolMSDataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchoolSubject
    {
        public int SSID { get; set; }
        public string Subjectcode { get; set; }
        public string Subjectname { get; set; }
        public string Category { get; set; }
        public int Schoolid { get; set; }
    }
}
