//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolMSDataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchoolAcademic
    {
        public int AcademicID { get; set; }
        public System.DateTime AcademicStartDate { get; set; }
        public System.DateTime AcademicEndDate { get; set; }
        public bool IsCurrentAcademic { get; set; }
        public int SchoolID { get; set; }
    }
}
