//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolMSDataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchoolClass
    {
        public int SCID { get; set; }
        public string Schoolclassname { get; set; }
        public int Displayorder { get; set; }
        public bool Status { get; set; }
        public int Schoolid { get; set; }
    }
}
