//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolMSDataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_communcation_Address
    {
        public long Student_Com_ID { get; set; }
        public long Student_ID { get; set; }
        public string House_Number { get; set; }
        public string Stread_Road { get; set; }
        public int Pin_Code { get; set; }
    
        public virtual Student_Personal_Details Student_Personal_Details { get; set; }
    }
}
