//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolMSDataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_Parent_Details
    {
        public long Student_Parent_ID { get; set; }
        public long Student_ID { get; set; }
        public string Mother_Name { get; set; }
        public string Father_Name { get; set; }
        public string Mother_Occupation { get; set; }
        public int Moblie_Number { get; set; }
        public string Email_ID { get; set; }
        public int Father_Aadhar_Number { get; set; }
        public bool Is_Login_Details_Sent { get; set; }
        public int Alternative_Moblie_number { get; set; }
        public string Father_Occupation { get; set; }
    
        public virtual Student_Personal_Details Student_Personal_Details { get; set; }
    }
}
