//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolMSDataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subject_Category
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Subject_Category()
        {
            this.SchoolSubjects = new HashSet<SchoolSubject>();
        }
    
        public int Category_id { get; set; }
        public string CategoryName { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<byte> SchoolId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SchoolSubject> SchoolSubjects { get; set; }
    }
}
